//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alharamApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alharamGate
    {
        public int gateNumber { get; set; }
        public string gateName { get; set; }
        public string gateDescription { get; set; }
        public string gateImage { get; set; }
    }
}
