//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alharamApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotel
    {
        public int hotelID { get; set; }
        public string hotelName { get; set; }
        public string hotelLocation { get; set; }
        public string hotelImg { get; set; }
    }
}
