//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alharamApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userFavorite
    {
        public int ID { get; set; }
        public string userIdentity { get; set; }
        public Nullable<int> favoriteID { get; set; }
    }
}
